on: [push, pull_request]

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            - name: Install Poetry via pip
              run: pip install poetry==1.2.0
            - name: Install dependencies
              run: poetry install --no-interaction --no-root

    lint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Run flake8
              run: poetry run flake8 .
            - name: Run pylint
              run: poetry run pylint .
            - name: Run mypy
              run: poetry run mypy .

    test:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Run tests
              run: poetry run pytest
